package openai

var ModelList = []string{
	"gpt-3.5-turbo",
	"gpt-3.5-turbo-16k",
	"gpt-3.5-turbo-instruct",
	"gpt-4",
	"gpt-4-turbo",
	"gpt-4.1",
	"gpt-4.1-mini",
	"gpt-4.1-nano",
	"gpt-4.5-preview",
	"gpt-4o",
	"gpt-4o-mini",
	"o1",
	"o1-mini",
	"o1-pro",
	"o3-mini",
	"o4-mini",
	"babbage-002",
	"chatgpt-4o-latest",
	"codex-mini-latest",
	"computer-use-preview",
	"davinci-002",
	"gpt-4o-audio-preview",
	"gpt-4o-mini-audio-preview",
	"gpt-4o-mini-realtime-preview",
	"gpt-4o-realtime-preview",
	"gpt-4o-mini-search-preview",
	"gpt-4o-search-preview",
	"gpt-4o-mini-transcribe",
	"gpt-4o-transcribe",
	"gpt-4o-mini-tts",
	"gpt-image-1",
	"dall-e-2",
	"dall-e-3",
	"omni-moderation-latest",
	"text-embedding-3-large",
	"text-embedding-3-small",
	"text-embedding-ada-002",
	"tts-1",
	"tts-1-hd",
	"whisper-1",
}

var ChannelName = "openai"
